echo sudo apt-get update_________________________________________________________________________________________________
sudo apt-get update
echo sudo apt-get upgrade________________________________________________________________________________________________
sudo apt-get upgrade
echo sudo apt-get install bluetooth______________________________________________________________________________________
sudo apt-get install bluetooth
echo sudo apt-get install python-cwiid___________________________________________________________________________________
sudo apt-get install python-cwiid
echo sudo apt-get install chromium_______________________________________________________________________________________
sudo apt-get install chromium
